version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin-container
    volumes:
      - ./v18/pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: oraclefedora@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    restart: unless-stopped
    networks:
      - odoo_network_18

networks:
  odoo_network_18:
    external: true
    name: odoo_network_18